apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
spec:
  template:
    spec:
      containers:
        - name: pal-tracker-container
          image: pravintumsare/pal-tracker:build-0.0.13
          env:
          - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
            valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: spring.datasource.hikari.maximumpoolsize
